### ISSUE TITLE
集成vant-weapp v0.5.12后，未能完整编译该组件

### ISSUE THREAD

**Issue by wangjikill** [wxajs/wxa#5]
## Description

 集成vant-weapp v0.5.12后，未能完整编译该组件

## Environment
  * @wxa/cli2 version: [2.0.5]
  * @wxa/core version: [2.0.0]
  * vant-weapp version: [0.5.12]
  
## Reproduce

  * npm i vant-weapp -S --production
 * 页面中集成
```
"usingComponents": {
  "van-button": "path/to/vant-weapp/dist/button/index"
}

<van-button type="default">默认按钮</van-button>
```
* wxa2 build

### Observed Results

 目录 node_modules\vant-weapp\dist\wxs\utils.wxs 文件import的文件，未能关联并编译
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs

  ```
//node_modules\vant-weapp\dist\wxs\utils.wxs 文件
  var bem = require('./bem.wxs').bem;
var memoize = require('./memoize.wxs').memoize;

function isSrc(url) {
  return url.indexOf('http') === 0 || url.indexOf('data:image') === 0 || url.indexOf('//') === 0;
}

module.exports = {
  bem: memoize(bem),
  isSrc: isSrc,
  memoize: memoize
};
  ```

**Comment by Genuifx** [comment]
hello, 有没有代码片段提供一下？

**Comment by wangjikill** [comment]
```
<script>
import { Page} from "@wxa/core";

@Page
export default class Test {
  onLoad(setting) {
    console.log(setting)
  }
}
</script>

<config>
{
    "navigationBarTitleText": "测试",
    "usingComponents": {
      "van-button": "vant-weapp/dist/button/index"
   }
}
</config>

<template>
  <van-button>sdfsdfdsf</van-button>
</template>

<style lang="scss">
</style>
```
这个是使用npm 安装vant-weapp后，页面集成的代码。之后又尝试npm安装wux-weapp,在页面集成后，在微信小程序开发工具预览时，同样会报错。
可能是webpack打包的配置不兼容吧，vant-weapp的包里，有这个文件，报错应该和里边的require有关系
```
//node_modules\vant-weapp\dist\wxs\utils.wxs 文件

var bem = require('./bem.wxs').bem;
var memoize = require('./memoize.wxs').memoize;

function isSrc(url) {
return url.indexOf('http') === 0 || url.indexOf('data:image') === 0 || url.indexOf('//') === 0;
}

module.exports = {
bem: memoize(bem),
isSrc: isSrc,
memoize: memoize
};
```

```
# 编译通过
$ wxa2 build
> Hey This is wxa@2.0.5, Running in development
> Building Project: app AT: 2019-5-31 18:04:06
> Done AT: 2019-5-31 18:04:07
```
```
# 微信小程序开发工具预览时，错误提示
VM227:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM227:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1559297048591:1304
window.onerror @ VM227:1
VM227:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM227:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1559297048591:1304
window.onerror @ VM227:1
VM227:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM227:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1559297048591:1304
window.onerror @ VM227:1
VM227:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM227:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1559297048591:1304
window.onerror @ VM227:1
VM227:1 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
console.error @ VM227:1
(anonymous) @ appservice?t=1559297048591:1159
$gwx @ appservice?t=1559297048591:1163
(anonymous) @ VM311:3
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
console.error @ VM227:1
(anonymous) @ appservice?t=1559297048591:1159
$gwx @ appservice?t=1559297048591:1163
(anonymous) @ VM311:6
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
console.error @ VM227:1
(anonymous) @ appservice?t=1559297048591:1159
$gwx @ appservice?t=1559297048591:1163
(anonymous) @ VM311:9
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
console.error @ VM227:1
(anonymous) @ appservice?t=1559297048591:1159
$gwx @ appservice?t=1559297048591:1163
(anonymous) @ VM311:12
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
console.error @ VM227:1
(anonymous) @ appservice?t=1559297048591:1159
$gwx @ appservice?t=1559297048591:1163
(anonymous) @ VM311:15
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
console.error @ VM227:1
(anonymous) @ appservice?t=1559297048591:1159
$gwx @ appservice?t=1559297048591:1163
(anonymous) @ VM311:18
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
console.error @ VM227:1
(anonymous) @ appservice?t=1559297048591:1159
$gwx @ appservice?t=1559297048591:1163
(anonymous) @ VM311:21
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
console.error @ VM227:1
(anonymous) @ appservice?t=1559297048591:1159
$gwx @ appservice?t=1559297048591:1163
(anonymous) @ VM311:24
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/vant-weapp/dist/loading/index.js" is not defined 
 Error: module "npm/vant-weapp/dist/loading/index.js" is not defined
    at require (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:1111425)
    at <anonymous>:65:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:64653/appservice/appservice?t=1559297048591:1390:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:64653/appservice/appservice?t=1559297048591:1402:20)
console.error @ VM227:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1559297048591:1304
window.onerror @ VM227:1
scriptLoaded @ appservice?t=1559297048591:1390
script.onload @ appservice?t=1559297048591:1402
VM227:1 jsEnginScriptError
Component is not found in path "npm/vant-weapp/dist/button/index" (using by "pages/test");onAppRoute
Error: Component is not found in path "npm/vant-weapp/dist/button/index" (using by "pages/test")
    at m (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:977684)
    at m (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:977870)
    at http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:995245
    at Object.t.addView (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:995791)
    at Function.value (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:1075831)
    at kt (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:1090058)
    at http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:1093600
    at It (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:1093663)
    at Function.<anonymous> (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:1096928)
    at i.<anonymous> (http://127.0.0.1:64653/appservice/__dev__/WAService.js:1:1068937)
console.error @ VM227:1
errorReport @ WAService.js:1
(anonymous) @ WAService.js:1
x @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1559297048591:1304
n.registerCallback.t @ appservice?t=1559297048591:1304
u.forEach.t @ appservice?t=1559297048591:1304
(anonymous) @ appservice?t=1559297048591:1304
a.onmessage @ appservice?t=1559297048591:1304
VM349:4 Fri May 31 2019 18:04:09 GMT+0800 (中国标准时间) 渲染层错误
VM349:5 TypeError: Cannot read property 'bem' of undefined
    at ./npm/vant-weapp/dist/wxs/utils.wxs
(anonymous) @ VM349:5
app.js:95 {errMsg: "getLocation:fail auth deny"}

```

**Comment by Genuifx** [comment]
![image](https://user-images.githubusercontent.com/10156994/58711898-0d4d3a00-83f2-11e9-8822-2ad76697439b.png)

原因是 `@wxa/cli2`没有对`.wxs`类型的文件进行依赖分析，识别为 other 类型了

**Comment by Genuifx** [comment]
解决方案：
1. cli 下个版本会增强wxs的支持，对wxs文件进行依赖分析，等待下个版本升级即可
2. 如果很着急要使用，可以临时在 `wxa.config.js` 加上以下配置解决：
```js
module.exports = {
    entry: ['src/app*', './node_modules/vant-weapp/dist/wxs/*'],
    use: [
        {
            test: /\.js$/,
            name: 'babel',
        },
    ]
};
```

**这里注意一下需要制定一下babel的规则，默认babel会对wxs进行编译，会导致额外的问题**

**Comment by wangjikill** [comment]
按照您的配置，./node_modules/vant-weapp/dist/wxs/*目录下的文件确实拷贝过去了，但是内容是“undefined”。
可否提供一个完整的配置，万分感谢。

**Comment by Genuifx** [comment]
这的确是一个缺陷，undefined 的问题， 得升级版本才能解决了。

**Comment by Genuifx** [comment]
@wangjikill 重新安装下 beta版本的cli `npm i @wxa/cli2@2.0.6-beta.1`

**Comment by wangjikill** [comment]
好的，我尝试一下
